kind: ConfigMap
apiVersion: v1
metadata:
  name: sonar-properties
data:
  sonar-project.properties: |
    sonar.organization=thepierrre
    sonar.host.url=https://sonarcloud.io
    sonar.projectKey=thepierrre_sample-spring-kotlin-microservice
