apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-project-version
  namespace: springboot-demo
spec:
  workspaces:
    - name: source
  params:
    - name: MAVEN_IMAGE
      type: string
      description: Maven base image
      default: docker.io/library/maven:3-eclipse-temurin-21-alpine
    - name: CONTEXT_DIR
      type: string
      description: The directory within the repository for sources on which we want to execute Maven goals.
      default: "."
  results:
    - name: version
      description: Project version read from pom.xml
  steps:
    - name: mvn-command
      image: $(params.MAVEN_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      script: |
        #!/usr/bin/env bash
        VERSION=$(/usr/bin/mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo -n $VERSION | tee $(results.version.path)
  securityContext:
    privileged: true
