apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-pipeline
spec:
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: https://github.com/thepierrre/demo-springboot-app
        - name: revision
          value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-dir
    - name: maven-build-artifact
      params:
        - name: MAVEN_IMAGE
          value: docker.io/library/maven:3-eclipse-temurin-21-alpine
        - name: GOALS
          value:
            - clean
            - test
            - package
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source-dir
        - name: maven-settings
          workspace: maven-settings-dir
        - name: maven-local-repo
          workspace: maven-local-m2
    - name: get-project-version
      taskRef:
        kind: Task
        name: get-project-version
      runAfter:
        - maven-build
      workspaces:
        - name: source
          workspace: source-dir
    - name: build-and-push-image
      params:
        - name: IMAGE
          value: default-route-openshift-image-registry.apps.ocp4.piotr-owczarc.com/springboot-demo/springboot-demo:$(tasks.get-project-version.results.version)
      runAfter:
        - get-project-version
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: source-dir

  workspaces:
    - name: source-dir
    - name: maven-settings-dir
    - name: maven-local-m2
