apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: allow-patch-tasks
 namespace: springboot-demo
subjects:
 - kind: ServiceAccount
   name: openshift-gitops-argocd-application-controller
   namespace: openshift-gitops
roleRef:
 kind: Role
 name: tekton-task-patcher
 apiGroup: rbac.authorization.k8s.io