apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
    pipeline.openshift.io/started-by: thepierrre
    pipeline.tekton.dev/release: f3dd478
  creationTimestamp: "2024-04-25T11:28:09Z"
  finalizers:
  - chains.tekton.dev
  generation: 1
  labels:
    app.kubernetes.io/instance: java-pipeline
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/memberOf: tasks
    tekton.dev/pipeline: java-pipeline
    tekton.dev/pipelineRun: java-pipeline-p0c951
    tekton.dev/pipelineTask: get-project-version
    tekton.dev/task: get-project-version
  name: java-pipeline-p0c951-get-project-version
  namespace: springboot-demo
  ownerReferences:
  - apiVersion: tekton.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: PipelineRun
    name: java-pipeline-p0c951
    uid: 2551260b-24cb-4cf3-8376-9c74f2617985
  resourceVersion: "2447715"
  uid: c2f7578f-3275-4a76-b9bb-543ad2de1064
spec:
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: get-project-version
  timeout: 1h0m0s
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: tekton-workspace
status:
  completionTime: "2024-04-25T11:28:15Z"
  conditions:
  - lastTransitionTime: "2024-04-25T11:28:15Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: java-pipeline-p0c951-get-project-version-pod
  provenance:
    featureFlags:
      AwaitSidecarReadiness: true
      Coschedule: workspaces
      DisableAffinityAssistant: true
      DisableCredsInit: false
      EnableAPIFields: beta
      EnableCELInWhenExpression: false
      EnableKeepPodOnCancel: false
      EnableParamEnum: false
      EnableProvenanceInStatus: true
      EnableStepActions: false
      EnableTektonOCIBundles: false
      EnforceNonfalsifiability: none
      MaxResultSize: 4096
      RequireGitSSHSecretKnownHosts: false
      ResultExtractionMethod: termination-message
      RunningInEnvWithInjectedSidecars: true
      ScopeWhenExpressionsToTask: false
      SendCloudEventsForRuns: false
      SetSecurityContext: false
      VerificationNoMatchPolicy: ignore
  results:
  - name: version
    type: string
    value: '[ERROR] Could not create local repository at /.m2/repository -> [Help
      1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with
      the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug
      logging. [ERROR] [ERROR] For more information about the errors and possible
      solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException'
  startTime: "2024-04-25T11:28:09Z"
  steps:
  - container: step-mvn-command
    imageID: docker.io/library/maven@sha256:72d3037cfd004de40832cfa4d36f02c01383dabbd12691eee069c52c950117e1
    name: mvn-command
    terminated:
      containerID: cri-o://44627512ab29214d7b22b2c71f4e266f412245d034a0404e7b9ad526515db3af
      exitCode: 0
      finishedAt: "2024-04-25T11:28:14Z"
      message: '[{"key":"version","value":"[ERROR] Could not create local repository
        at /.m2/repository -\u003e [Help 1] [ERROR] [ERROR] To see the full stack
        trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven
        using the -X switch to enable full debug logging. [ERROR] [ERROR] For more
        information about the errors and possible solutions, please read the following
        articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException","type":1}]'
      reason: Completed
      startedAt: "2024-04-25T11:28:13Z"
  taskSpec:
    params:
    - default: docker.io/library/maven:3-eclipse-temurin-21-alpine
      description: Maven base image
      name: MAVEN_IMAGE
      type: string
    - default: .
      description: The directory within the repository for sources on which we want
        to execute Maven goals.
      name: CONTEXT_DIR
      type: string
    results:
    - description: Project version read from pom.xml
      name: version
      type: string
    steps:
    - computeResources: {}
      image: docker.io/library/maven:3-eclipse-temurin-21-alpine
      name: mvn-command
      script: |
        #!/usr/bin/env bash
        VERSION=$(/usr/bin/mvn mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo -n $VERSION | tee /tekton/results/version
      workingDir: /workspace/source/.
    workspaces:
    - name: source
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
    pipeline.openshift.io/started-by: thepierrre
    pipeline.tekton.dev/release: f3dd478
  creationTimestamp: "2024-04-25T11:28:09Z"
  finalizers:
  - chains.tekton.dev
  generation: 1
  labels:
    app.kubernetes.io/instance: java-pipeline
    app.kubernetes.io/managed-by: tekton-pipelines
    tekton.dev/memberOf: tasks
    tekton.dev/pipeline: java-pipeline
    tekton.dev/pipelineRun: java-pipeline-p0c951
    tekton.dev/pipelineTask: get-project-version
    tekton.dev/task: get-project-version
  name: java-pipeline-p0c951-get-project-version
  namespace: springboot-demo
  ownerReferences:
  - apiVersion: tekton.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: PipelineRun
    name: java-pipeline-p0c951
    uid: 2551260b-24cb-4cf3-8376-9c74f2617985
  resourceVersion: "2447715"
  uid: c2f7578f-3275-4a76-b9bb-543ad2de1064
spec:
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: get-project-version
  timeout: 1h0m0s
  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: tekton-workspace
status:
  completionTime: "2024-04-25T11:28:15Z"
  conditions:
  - lastTransitionTime: "2024-04-25T11:28:15Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  podName: java-pipeline-p0c951-get-project-version-pod
  provenance:
    featureFlags:
      AwaitSidecarReadiness: true
      Coschedule: workspaces
      DisableAffinityAssistant: true
      DisableCredsInit: false
      EnableAPIFields: beta
      EnableCELInWhenExpression: false
      EnableKeepPodOnCancel: false
      EnableParamEnum: false
      EnableProvenanceInStatus: true
      EnableStepActions: false
      EnableTektonOCIBundles: false
      EnforceNonfalsifiability: none
      MaxResultSize: 4096
      RequireGitSSHSecretKnownHosts: false
      ResultExtractionMethod: termination-message
      RunningInEnvWithInjectedSidecars: true
      ScopeWhenExpressionsToTask: false
      SendCloudEventsForRuns: false
      SetSecurityContext: false
      VerificationNoMatchPolicy: ignore
  results:
  - name: version
    type: string
    value: '[ERROR] Could not create local repository at /.m2/repository -> [Help
      1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with
      the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug
      logging. [ERROR] [ERROR] For more information about the errors and possible
      solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException'
  startTime: "2024-04-25T11:28:09Z"
  steps:
  - container: step-mvn-command
    imageID: docker.io/library/maven@sha256:72d3037cfd004de40832cfa4d36f02c01383dabbd12691eee069c52c950117e1
    name: mvn-command
    terminated:
      containerID: cri-o://44627512ab29214d7b22b2c71f4e266f412245d034a0404e7b9ad526515db3af
      exitCode: 0
      finishedAt: "2024-04-25T11:28:14Z"
      message: '[{"key":"version","value":"[ERROR] Could not create local repository
        at /.m2/repository -\u003e [Help 1] [ERROR] [ERROR] To see the full stack
        trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven
        using the -X switch to enable full debug logging. [ERROR] [ERROR] For more
        information about the errors and possible solutions, please read the following
        articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException","type":1}]'
      reason: Completed
      startedAt: "2024-04-25T11:28:13Z"
  taskSpec:
    params:
    - default: docker.io/library/maven:3-eclipse-temurin-21-alpine
      description: Maven base image
      name: MAVEN_IMAGE
      type: string
    - default: .
      description: The directory within the repository for sources on which we want
        to execute Maven goals.
      name: CONTEXT_DIR
      type: string
    results:
    - description: Project version read from pom.xml
      name: version
      type: string
    steps:
    - computeResources: {}
      image: docker.io/library/maven:3-eclipse-temurin-21-alpine
      name: mvn-command
      script: |
        #!/usr/bin/env bash
        VERSION=$(/usr/bin/mvn mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo -n $VERSION | tee /tekton/results/version
      workingDir: /workspace/source/.
    workspaces:
    - name: source
