kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-workspace
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
