apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{"include.release.openshift.io/ibm-cloud-managed":"true","include.release.openshift.io/self-managed-high-availability":"true","include.release.openshift.io/single-node-developer":"true","release.openshift.io/create-only":"true"},"creationTimestamp":"2024-09-16T14:12:29Z","generation":7,"name":"cluster","ownerReferences":[{"apiVersion":"config.openshift.io/v1","kind":"ClusterVersion","name":"version","uid":"f32db013-2609-418d-ab5b-03b1f9cb1a04"}],"resourceVersion":"256303","uid":"c1f89be9-4e78-47aa-86f1-e9b70fefe57d"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"htpasswd"}},"mappingMethod":"claim","name":"Local","type":"HTPasswd"},{"github":{"clientID":"938c3e25ff648402abe7","clientSecret":{"name":"github"},"organizations":["piotrowczarc"]},"mappingMethod":"claim","name":"github","type":"GitHub"}]}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-09-16T14:12:29Z"
  generation: 8
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: f32db013-2609-418d-ab5b-03b1f9cb1a04
  resourceVersion: "270034"
  uid: c1f89be9-4e78-47aa-86f1-e9b70fefe57d
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htpasswd
    mappingMethod: claim
    name: Local
    type: HTPasswd
  - github:
      clientID: 938c3e25ff648402abe7
      clientSecret:
        name: github
      organizations:
      - piotrowczarc
    mappingMethod: claim
    name: github
    type: GitHub
