apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build-and-push-java-image-pipeline
  namespace: openshift-gitops
spec:
  syncPolicy: 
    automated:
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/thepierrre/openshift
      path: cicd/java
      targetRevision: main
  project: default



