apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-pipeline
  namespace: {{ .Values.namespace }}
spec:
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: {{ .Values.git.repository }}
        - name: revision
          value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-dir
    - name: maven-build
      params:
        - name: MAVEN_IMAGE
          value: docker.io/library/maven:3-eclipse-temurin-21-alpine
        - name: GOALS
          value:
            - clean
            - test
            - package
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source-dir
        - name: maven-settings
          workspace: maven-settings-dir
        - name: maven-local-repo
          workspace: maven-local-m2
    - name: get-project-version
      taskRef:
        kind: Task
        name: get-project-version
      runAfter:
        - maven-build
      workspaces:
        - name: source
          workspace: source-dir
    - name: build-and-push-image
      params:
        - name: IMAGE
          value: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      runAfter:
        - get-project-version
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: source-dir

  workspaces:
    - name: source-dir
    - name: maven-settings-dir
    - name: maven-local-m2
