kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven-settings-workspace
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
