apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.appName }}.{{ .Values.host }}
  to:
    kind: Service
    name: {{ .Values.appName }}
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
