# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: tekton-trigger-reader
# rules:
#   - apiGroups: ["triggers.tekton.dev"]
#     resources: ["clusterinterceptors"]
#     verbs: ["get", "list", "watch"]