# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: tekton-trigger-reader-binding
#   namespace: java-pipelines
# subjects:
#   - kind: ServiceAccount
#     name: builder
#     namespace: java-pipelines
# roleRef:
#   kind: Role
#   name: tekton-trigger-reader
#   apiGroup: rbac.authorization.k8s.io