apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-trigger-template
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  params:
    - name: git-revision
      description: "The git revision"
      default: main
    - name: git-repo-url
      description: "The git repository url"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sample-java-pipeline-run-
      spec:
        pipelineRef:
          name: java-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: source-dir
            persistentVolumeClaim:
              claimName: tekton-workspace
          - name: maven-settings-dir
            persistentVolumeClaim:
              claimName: maven-settings-workspace
          - name: maven-local-m2
            persistentVolumeClaim:
              claimName: maven-local-repo-workspace
