apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-trigger-template
  namespace: java-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: java-build-and-push-image-pipeline-run-
      spec:
        pipelineRef:
          name: java-build-and-push-image
        workspaces:
          - name: source-dir
            persistentVolumeClaim:
              claimName: tekton-workspace
          - name: maven-settings-dir
            persistentVolumeClaim:
              claimName: maven-settings-workspace
          - name: maven-local-m2
            persistentVolumeClaim:
              claimName: maven-local-repo-workspace
