apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
  name: el-github-event-listener
  namespace: gymtracker
spec:
  host: el-github-event-listener-{{ .Values.namespace }}.{{ .Values.host }}
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-github-event-listener