apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-build-and-push-image
  namespace: java-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  params:
    - name: url
      description: "Git repository url"
      default: https://github.com/thepierrre/workout-tracker-backend
    - name: revision
      description: "Git revision"
      default: release
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-dir
    - name: build-artifact
      params:
        - name: MAVEN_IMAGE
          value: docker.io/library/maven:3-eclipse-temurin-21-alpine
        - name: GOALS
          value:
            - clean
            - test
            - package
      taskRef:
        kind: Task
        name: maven
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: source-dir
        - name: maven-settings
          workspace: maven-settings-dir
        # - name: maven-local-repo
        #   workspace: maven-local-m2
    - name: get-project-version
      taskRef:
        kind: Task
        name: get-project-version
      runAfter:
        - build-artifact
      workspaces:
        - name: source
          workspace: source-dir
    - name: build-and-push-image
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc.cluster.local:5000/gym-tracker/gym-tracker-java:$(tasks.get-project-version.results.version)
      runAfter:
        - get-project-version
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: source-dir

  workspaces:
    - name: source-dir
    - name: maven-settings-dir
    # - name: maven-local-m2
