kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: maven-local-repo-workspace
  namespace: gymtracker
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
