apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: push-java-image-pipeline
spec:
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: 'https://piotrowczarc.github.io/helm-charts/'
      chart: cicd
      targetRevision: 0.3.0
      helm:
        valueFiles:
          - $values/helm/pipeline-values.yaml
    - repoURL: https://github.com/thepierrre/demo-springboot-app
      targetRevision: HEAD
      ref: values
  project: default


# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: push-java-image-pipeline
# spec:
#   destination:
#     server: https://kubernetes.default.svc
#   source:
#     repoURL: 'https://github.com/thepierrre/openshift'
#     path: ./springboot-cicd/cicd
#     targetRevision: HEAD
#   project: default


