apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-demo
  namespace: openshift-gitops
spec:
  syncPolicy: 
    automated:
      selfHeal: true
  destination:
    namespace: springboot-demo
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://piotrowczarc.github.io/helm-charts/
      chart: springboot
      targetRevision: 0.4.0
      helm:
        valueFiles:
          - $values/helm/application-values.yaml
    - repoURL: https://github.com/thepierrre/demo-springboot-app
      targetRevision: HEAD
      ref: values
  project: default
